documentcloud repos have moved
The two referenced documentcloud repos have moved.  This is the volo error I receive.

    > volo add -amd documentcloud/underscore exports=_
    api.github.com/repos/documentcloud/underscore/tags does not exist. Is this a private repo [n]? n
    Error: api.github.com/repos/documentcloud/underscore/tags does not exist. Is this a private repo [n]?

I have fixed this documentation.